### ISSUE TITLE
More content for flashcards, level and book

### ISSUE THREAD

**Issue by florentianayuwono** [florentianayuwono/LiteUp#2]
inside the `lib/constants/text.dart`, we will define all out flashcards, level and book content. However, now it is still quite empty.

Idea: How about we have like Indonesian history/literature/etc. as the flashcards content (provide both English and Bahasa version)? Then for the book prize we can have like Indonesian/English classic literature as well.
@aliciamichellew @liviamil

**Comment by liviamil** [comment]
For flashcards, since we can use the levels as the encouraging factors, the "appeal" for the content does not matter as much. So, I would not mind using Indonesian history/literature for the contents. For the book prize however, I think a "prize" should be appealing to the user. So I'm not sure if a classical book is the way to go, as they tend to be lengthy and more advanced (difficult to understand for beginners). But this is just my subjective take on it.

On that note, are we making "complete book" as one of the conditions to unlock the next level? Because if we are, it will make choosing the "right" book as prize more important. Books are quite lengthy, I feel like unless people are actually interested in the book, they won't bother finish reading it, hence defeating the aim of our app. Some roundabout ideas I thought of are:
1. Make the "complete book" as optional condition to unlock next level. i.e. user will get book 1 and unlock level 2 at once after user finish level 1.
2. Point collections per level as reward that can be collected and redeemed with a book of their choice. 

Let me know what you guys think of this.

**Comment by florentianayuwono** [comment]
I agree for the book prize that it needs not be a classical thingy. Liberty is given to the assignee of this issue. We can have a selection of books and let user choose one book per level completed to unlock. The variety of books to choose itself will increase according to the level unlocked.

For now, we can just have a stub of 2-3 paragraphs to count as a book, depends on how niat the person assigned to this issue haha.

1. Agree. The book is just a prize for them to read anytime they want. User can automatically start on level 2.
2. We can have both. So user can unlock one book per level, but they will also accumulate points as they continue unlocking more levels. These points can be used to redeem more attractive prizes.

Do you want to be in charge of this issue then @liviamil?

**Comment by liviamil** [comment]
Ok noted, sure, I'll take it!
